version: '3.7'
services:
  frontend:
    image: frontend
    build: ./frontend
  backend:
    image: backend
    build: ./backend
    environment:
        DATABASE_URI: mysql+pymysql://root:password@database:3306/users
        SECRET KEY: password
  database:
    image: database
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=password
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
