version: '3.7'
services:
  frontend:
    image: frontend
    build: ./frontend
    depends_on:
      - backend

  backend:
    image: backend
    build: ./backend
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - mysql

  mysql:
    image: mysql
    build: ./database
    environment:
      - MYSQL_ADMIN_PASSWORD=${MYSQL_ADMIN_PASSWORD}
 
  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
